// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/accordion/Accordion.vue')['default']
    AccordionRow: typeof import('./components/accordion/AccordionRow.vue')['default']
    AnimateComponent: typeof import('./components/AnimateComponent.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Back: typeof import('./components/Back.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    'Card copy': typeof import('./components/Card copy.vue')['default']
    ClickCopy: typeof import('./components/ClickCopy.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconTip: typeof import('./components/IconTip.vue')['default']
    ImageCard: typeof import('./components/ImageCard.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MyCanvas: typeof import('./components/canvas/MyCanvas.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PureCard: typeof import('./components/PureCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabPane: typeof import('./components/tabs/TabPane.vue')['default']
    Tabs: typeof import('./components/tabs/Tabs.vue')['default']
    ToolTip: typeof import('./components/tooltips/ToolTip.vue')['default']
    ToolTipsProvider: typeof import('./components/tooltips/ToolTipsProvider.vue')['default']
  }
}

export {}
